# Supported funding model for Nicztin platform

github: [nicztin]  # Replace with up to 4 GitHub Sponsors-enabled usernames
patreon: nicztin   # Replace with a single Patreon username
open_collective: nicztin  # Replace with a single Open Collective username
ko_fi: nicztin     # Replace with a single Ko-fi username
tidelift: npm/nicztin  # Replace with a Tidelift platform-name/package-name
community_bridge: nicztin-project  # Replace with your Community Bridge project-name
liberapay: nicztin   # Replace with a single Liberapay username
issuehunt: nicztin   # Replace with a single IssueHunt username
lfx_crowdfunding: nicztin-project  # Replace with your LFX Crowdfunding project-name
polar: nicztin       # Replace with a single Polar username
buy_me_a_coffee: nicztin  # Replace with a single Buy Me a Coffee username
thanks_dev: nicztin  # Replace with a single thanks.dev username
custom:
  - https://www.paypal.com/myaccount/money/cards/CC-4URFUH8V4QCHE
  - https://lnk.bio/neatten
